name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'quantum'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'documentation'
      - 'doc'
      - 'test'
      - 'tests'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'quantum'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'documentation'
      - 'doc'
      - 'test'
      - 'tests'
  default: patch

template: |
  ## QuantRS2 $RESOLVED_VERSION
  
  $CHANGES
  
  **Full Changelog**: https://github.com/cool-japan/quantrs/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION